# Generated by Django 3.2 on 2021-06-14 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_rename_emali_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='제목')),
                ('contents', models.TextField(verbose_name='내용')),
                ('registered_time', models.DateTimeField(auto_now_add=True, verbose_name='등록 시간')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='작성자')),
            ],
            options={
                'verbose_name': '아이티뱅크 개시글',
                'verbose_name_plural': '아이티뱅크 개시글',
                'db_table': 'Django_Tutorial_01_Project_board',
            },
        ),
    ]
